// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Folder is the predicate function for folder builders.
type Folder func(*sql.Selector)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)
