package main

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/altierawr/notebook/ent"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy []*ent.FolderOrder, where *ent.FolderWhereInput) (*ent.FolderConnection, error) {
	return r.client.Folder.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithFolderOrder(orderBy),
			ent.WithFolderFilter(where.Filter),
		)
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy []*ent.NoteOrder, where *ent.NoteWhereInput) (*ent.NoteConnection, error) {
	return r.client.Note.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithNoteOrder(orderBy),
			ent.WithNoteFilter(where.Filter),
		)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
