package notebook

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/altierawr/notebook/ent"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input ent.CreateNoteInput) (*ent.Note, error) {
	client := ent.FromContext(ctx)
	return client.Note.Create().SetInput(input).Save(ctx)
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id int, input ent.UpdateNoteInput) (*ent.Note, error) {
	client := ent.FromContext(ctx)
	return client.Note.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input ent.CreateFolderInput) (*ent.Folder, error) {
	client := ent.FromContext(ctx)
	return client.Folder.Create().SetInput(input).Save(ctx)
}

// UpdateFolder is the resolver for the updateFolder field.
func (r *mutationResolver) UpdateFolder(ctx context.Context, id int, input ent.UpdateFolderInput) (*ent.Folder, error) {
	client := ent.FromContext(ctx)
	return client.Folder.UpdateOneID(id).SetInput(input).Save(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
