// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/altierawr/notebook/ent/folder"
)

// Folder is the model entity for the Folder schema.
type Folder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FolderQuery when eager-loading is set.
	Edges        FolderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FolderEdges holds the relations/edges for other nodes in the graph.
type FolderEdges struct {
	// Folders holds the value of the folders edge.
	Folders []*Folder `json:"folders,omitempty"`
	// Parent holds the value of the parent edge.
	Parent []*Folder `json:"parent,omitempty"`
	// Notes holds the value of the notes edge.
	Notes []*Note `json:"notes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedFolders map[string][]*Folder
	namedParent  map[string][]*Folder
	namedNotes   map[string][]*Note
}

// FoldersOrErr returns the Folders value or an error if the edge
// was not loaded in eager-loading.
func (e FolderEdges) FoldersOrErr() ([]*Folder, error) {
	if e.loadedTypes[0] {
		return e.Folders, nil
	}
	return nil, &NotLoadedError{edge: "folders"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading.
func (e FolderEdges) ParentOrErr() ([]*Folder, error) {
	if e.loadedTypes[1] {
		return e.Parent, nil
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e FolderEdges) NotesOrErr() ([]*Note, error) {
	if e.loadedTypes[2] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Folder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case folder.FieldID:
			values[i] = new(sql.NullInt64)
		case folder.FieldTitle:
			values[i] = new(sql.NullString)
		case folder.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Folder fields.
func (f *Folder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case folder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			f.ID = int(value.Int64)
		case folder.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				f.Title = value.String
			}
		case folder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				f.CreatedAt = value.Time
			}
		default:
			f.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Folder.
// This includes values selected through modifiers, order, etc.
func (f *Folder) Value(name string) (ent.Value, error) {
	return f.selectValues.Get(name)
}

// QueryFolders queries the "folders" edge of the Folder entity.
func (f *Folder) QueryFolders() *FolderQuery {
	return NewFolderClient(f.config).QueryFolders(f)
}

// QueryParent queries the "parent" edge of the Folder entity.
func (f *Folder) QueryParent() *FolderQuery {
	return NewFolderClient(f.config).QueryParent(f)
}

// QueryNotes queries the "notes" edge of the Folder entity.
func (f *Folder) QueryNotes() *NoteQuery {
	return NewFolderClient(f.config).QueryNotes(f)
}

// Update returns a builder for updating this Folder.
// Note that you need to call Folder.Unwrap() before calling this method if this Folder
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Folder) Update() *FolderUpdateOne {
	return NewFolderClient(f.config).UpdateOne(f)
}

// Unwrap unwraps the Folder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *Folder) Unwrap() *Folder {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Folder is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Folder) String() string {
	var builder strings.Builder
	builder.WriteString("Folder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", f.ID))
	builder.WriteString("title=")
	builder.WriteString(f.Title)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(f.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedFolders returns the Folders named value or an error if the edge was not
// loaded in eager-loading with this name.
func (f *Folder) NamedFolders(name string) ([]*Folder, error) {
	if f.Edges.namedFolders == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := f.Edges.namedFolders[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (f *Folder) appendNamedFolders(name string, edges ...*Folder) {
	if f.Edges.namedFolders == nil {
		f.Edges.namedFolders = make(map[string][]*Folder)
	}
	if len(edges) == 0 {
		f.Edges.namedFolders[name] = []*Folder{}
	} else {
		f.Edges.namedFolders[name] = append(f.Edges.namedFolders[name], edges...)
	}
}

// NamedParent returns the Parent named value or an error if the edge was not
// loaded in eager-loading with this name.
func (f *Folder) NamedParent(name string) ([]*Folder, error) {
	if f.Edges.namedParent == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := f.Edges.namedParent[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (f *Folder) appendNamedParent(name string, edges ...*Folder) {
	if f.Edges.namedParent == nil {
		f.Edges.namedParent = make(map[string][]*Folder)
	}
	if len(edges) == 0 {
		f.Edges.namedParent[name] = []*Folder{}
	} else {
		f.Edges.namedParent[name] = append(f.Edges.namedParent[name], edges...)
	}
}

// NamedNotes returns the Notes named value or an error if the edge was not
// loaded in eager-loading with this name.
func (f *Folder) NamedNotes(name string) ([]*Note, error) {
	if f.Edges.namedNotes == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := f.Edges.namedNotes[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (f *Folder) appendNamedNotes(name string, edges ...*Note) {
	if f.Edges.namedNotes == nil {
		f.Edges.namedNotes = make(map[string][]*Note)
	}
	if len(edges) == 0 {
		f.Edges.namedNotes[name] = []*Note{}
	} else {
		f.Edges.namedNotes[name] = append(f.Edges.namedNotes[name], edges...)
	}
}

// Folders is a parsable slice of Folder.
type Folders []*Folder
