// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/altierawr/notebook/ent/folder"
	"github.com/altierawr/notebook/ent/note"
	"github.com/altierawr/notebook/ent/predicate"
)

// FolderUpdate is the builder for updating Folder entities.
type FolderUpdate struct {
	config
	hooks    []Hook
	mutation *FolderMutation
}

// Where appends a list predicates to the FolderUpdate builder.
func (fu *FolderUpdate) Where(ps ...predicate.Folder) *FolderUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetTitle sets the "title" field.
func (fu *FolderUpdate) SetTitle(s string) *FolderUpdate {
	fu.mutation.SetTitle(s)
	return fu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (fu *FolderUpdate) SetNillableTitle(s *string) *FolderUpdate {
	if s != nil {
		fu.SetTitle(*s)
	}
	return fu
}

// AddFolderIDs adds the "folders" edge to the Folder entity by IDs.
func (fu *FolderUpdate) AddFolderIDs(ids ...int) *FolderUpdate {
	fu.mutation.AddFolderIDs(ids...)
	return fu
}

// AddFolders adds the "folders" edges to the Folder entity.
func (fu *FolderUpdate) AddFolders(f ...*Folder) *FolderUpdate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fu.AddFolderIDs(ids...)
}

// AddParentIDs adds the "parent" edge to the Folder entity by IDs.
func (fu *FolderUpdate) AddParentIDs(ids ...int) *FolderUpdate {
	fu.mutation.AddParentIDs(ids...)
	return fu
}

// AddParent adds the "parent" edges to the Folder entity.
func (fu *FolderUpdate) AddParent(f ...*Folder) *FolderUpdate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fu.AddParentIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (fu *FolderUpdate) AddNoteIDs(ids ...int) *FolderUpdate {
	fu.mutation.AddNoteIDs(ids...)
	return fu
}

// AddNotes adds the "notes" edges to the Note entity.
func (fu *FolderUpdate) AddNotes(n ...*Note) *FolderUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return fu.AddNoteIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (fu *FolderUpdate) Mutation() *FolderMutation {
	return fu.mutation
}

// ClearFolders clears all "folders" edges to the Folder entity.
func (fu *FolderUpdate) ClearFolders() *FolderUpdate {
	fu.mutation.ClearFolders()
	return fu
}

// RemoveFolderIDs removes the "folders" edge to Folder entities by IDs.
func (fu *FolderUpdate) RemoveFolderIDs(ids ...int) *FolderUpdate {
	fu.mutation.RemoveFolderIDs(ids...)
	return fu
}

// RemoveFolders removes "folders" edges to Folder entities.
func (fu *FolderUpdate) RemoveFolders(f ...*Folder) *FolderUpdate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fu.RemoveFolderIDs(ids...)
}

// ClearParent clears all "parent" edges to the Folder entity.
func (fu *FolderUpdate) ClearParent() *FolderUpdate {
	fu.mutation.ClearParent()
	return fu
}

// RemoveParentIDs removes the "parent" edge to Folder entities by IDs.
func (fu *FolderUpdate) RemoveParentIDs(ids ...int) *FolderUpdate {
	fu.mutation.RemoveParentIDs(ids...)
	return fu
}

// RemoveParent removes "parent" edges to Folder entities.
func (fu *FolderUpdate) RemoveParent(f ...*Folder) *FolderUpdate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fu.RemoveParentIDs(ids...)
}

// ClearNotes clears all "notes" edges to the Note entity.
func (fu *FolderUpdate) ClearNotes() *FolderUpdate {
	fu.mutation.ClearNotes()
	return fu
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (fu *FolderUpdate) RemoveNoteIDs(ids ...int) *FolderUpdate {
	fu.mutation.RemoveNoteIDs(ids...)
	return fu
}

// RemoveNotes removes "notes" edges to Note entities.
func (fu *FolderUpdate) RemoveNotes(n ...*Note) *FolderUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return fu.RemoveNoteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FolderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FolderUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FolderUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FolderUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FolderUpdate) check() error {
	if v, ok := fu.mutation.Title(); ok {
		if err := folder.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Folder.title": %w`, err)}
		}
	}
	return nil
}

func (fu *FolderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(folder.Table, folder.Columns, sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Title(); ok {
		_spec.SetField(folder.FieldTitle, field.TypeString, value)
	}
	if fu.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.FoldersTable,
			Columns: folder.FoldersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedFoldersIDs(); len(nodes) > 0 && !fu.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.FoldersTable,
			Columns: folder.FoldersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.FoldersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.FoldersTable,
			Columns: folder.FoldersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: folder.ParentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedParentIDs(); len(nodes) > 0 && !fu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: folder.ParentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: folder.ParentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.NotesTable,
			Columns: folder.NotesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedNotesIDs(); len(nodes) > 0 && !fu.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.NotesTable,
			Columns: folder.NotesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.NotesTable,
			Columns: folder.NotesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{folder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FolderUpdateOne is the builder for updating a single Folder entity.
type FolderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FolderMutation
}

// SetTitle sets the "title" field.
func (fuo *FolderUpdateOne) SetTitle(s string) *FolderUpdateOne {
	fuo.mutation.SetTitle(s)
	return fuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (fuo *FolderUpdateOne) SetNillableTitle(s *string) *FolderUpdateOne {
	if s != nil {
		fuo.SetTitle(*s)
	}
	return fuo
}

// AddFolderIDs adds the "folders" edge to the Folder entity by IDs.
func (fuo *FolderUpdateOne) AddFolderIDs(ids ...int) *FolderUpdateOne {
	fuo.mutation.AddFolderIDs(ids...)
	return fuo
}

// AddFolders adds the "folders" edges to the Folder entity.
func (fuo *FolderUpdateOne) AddFolders(f ...*Folder) *FolderUpdateOne {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fuo.AddFolderIDs(ids...)
}

// AddParentIDs adds the "parent" edge to the Folder entity by IDs.
func (fuo *FolderUpdateOne) AddParentIDs(ids ...int) *FolderUpdateOne {
	fuo.mutation.AddParentIDs(ids...)
	return fuo
}

// AddParent adds the "parent" edges to the Folder entity.
func (fuo *FolderUpdateOne) AddParent(f ...*Folder) *FolderUpdateOne {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fuo.AddParentIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (fuo *FolderUpdateOne) AddNoteIDs(ids ...int) *FolderUpdateOne {
	fuo.mutation.AddNoteIDs(ids...)
	return fuo
}

// AddNotes adds the "notes" edges to the Note entity.
func (fuo *FolderUpdateOne) AddNotes(n ...*Note) *FolderUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return fuo.AddNoteIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (fuo *FolderUpdateOne) Mutation() *FolderMutation {
	return fuo.mutation
}

// ClearFolders clears all "folders" edges to the Folder entity.
func (fuo *FolderUpdateOne) ClearFolders() *FolderUpdateOne {
	fuo.mutation.ClearFolders()
	return fuo
}

// RemoveFolderIDs removes the "folders" edge to Folder entities by IDs.
func (fuo *FolderUpdateOne) RemoveFolderIDs(ids ...int) *FolderUpdateOne {
	fuo.mutation.RemoveFolderIDs(ids...)
	return fuo
}

// RemoveFolders removes "folders" edges to Folder entities.
func (fuo *FolderUpdateOne) RemoveFolders(f ...*Folder) *FolderUpdateOne {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fuo.RemoveFolderIDs(ids...)
}

// ClearParent clears all "parent" edges to the Folder entity.
func (fuo *FolderUpdateOne) ClearParent() *FolderUpdateOne {
	fuo.mutation.ClearParent()
	return fuo
}

// RemoveParentIDs removes the "parent" edge to Folder entities by IDs.
func (fuo *FolderUpdateOne) RemoveParentIDs(ids ...int) *FolderUpdateOne {
	fuo.mutation.RemoveParentIDs(ids...)
	return fuo
}

// RemoveParent removes "parent" edges to Folder entities.
func (fuo *FolderUpdateOne) RemoveParent(f ...*Folder) *FolderUpdateOne {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fuo.RemoveParentIDs(ids...)
}

// ClearNotes clears all "notes" edges to the Note entity.
func (fuo *FolderUpdateOne) ClearNotes() *FolderUpdateOne {
	fuo.mutation.ClearNotes()
	return fuo
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (fuo *FolderUpdateOne) RemoveNoteIDs(ids ...int) *FolderUpdateOne {
	fuo.mutation.RemoveNoteIDs(ids...)
	return fuo
}

// RemoveNotes removes "notes" edges to Note entities.
func (fuo *FolderUpdateOne) RemoveNotes(n ...*Note) *FolderUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return fuo.RemoveNoteIDs(ids...)
}

// Where appends a list predicates to the FolderUpdate builder.
func (fuo *FolderUpdateOne) Where(ps ...predicate.Folder) *FolderUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FolderUpdateOne) Select(field string, fields ...string) *FolderUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Folder entity.
func (fuo *FolderUpdateOne) Save(ctx context.Context) (*Folder, error) {
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FolderUpdateOne) SaveX(ctx context.Context) *Folder {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FolderUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FolderUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FolderUpdateOne) check() error {
	if v, ok := fuo.mutation.Title(); ok {
		if err := folder.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Folder.title": %w`, err)}
		}
	}
	return nil
}

func (fuo *FolderUpdateOne) sqlSave(ctx context.Context) (_node *Folder, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(folder.Table, folder.Columns, sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Folder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, folder.FieldID)
		for _, f := range fields {
			if !folder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != folder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Title(); ok {
		_spec.SetField(folder.FieldTitle, field.TypeString, value)
	}
	if fuo.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.FoldersTable,
			Columns: folder.FoldersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedFoldersIDs(); len(nodes) > 0 && !fuo.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.FoldersTable,
			Columns: folder.FoldersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.FoldersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.FoldersTable,
			Columns: folder.FoldersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: folder.ParentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedParentIDs(); len(nodes) > 0 && !fuo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: folder.ParentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: folder.ParentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.NotesTable,
			Columns: folder.NotesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedNotesIDs(); len(nodes) > 0 && !fuo.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.NotesTable,
			Columns: folder.NotesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   folder.NotesTable,
			Columns: folder.NotesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Folder{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{folder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
