// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (f *Folder) Folders(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy []*FolderOrder, where *FolderWhereInput,
) (*FolderConnection, error) {
	opts := []FolderPaginateOption{
		WithFolderOrder(orderBy),
		WithFolderFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := f.Edges.totalCount[0][alias]
	if nodes, err := f.NamedFolders(alias); err == nil || hasTotalCount {
		pager, err := newFolderPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &FolderConnection{Edges: []*FolderEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return f.QueryFolders().Paginate(ctx, after, first, before, last, opts...)
}

func (f *Folder) Parent(ctx context.Context) (result []*Folder, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = f.NamedParent(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = f.Edges.ParentOrErr()
	}
	if IsNotLoaded(err) {
		result, err = f.QueryParent().All(ctx)
	}
	return result, err
}

func (f *Folder) Notes(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy []*NoteOrder, where *NoteWhereInput,
) (*NoteConnection, error) {
	opts := []NotePaginateOption{
		WithNoteOrder(orderBy),
		WithNoteFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := f.Edges.totalCount[2][alias]
	if nodes, err := f.NamedNotes(alias); err == nil || hasTotalCount {
		pager, err := newNotePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &NoteConnection{Edges: []*NoteEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return f.QueryNotes().Paginate(ctx, after, first, before, last, opts...)
}

func (n *Note) Parent(ctx context.Context) (result []*Folder, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = n.NamedParent(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = n.Edges.ParentOrErr()
	}
	if IsNotLoaded(err) {
		result, err = n.QueryParent().All(ctx)
	}
	return result, err
}
