// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (f *Folder) Folders(ctx context.Context) (result []*Folder, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = f.NamedFolders(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = f.Edges.FoldersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = f.QueryFolders().All(ctx)
	}
	return result, err
}

func (f *Folder) Parent(ctx context.Context) (result []*Folder, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = f.NamedParent(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = f.Edges.ParentOrErr()
	}
	if IsNotLoaded(err) {
		result, err = f.QueryParent().All(ctx)
	}
	return result, err
}

func (f *Folder) Notes(ctx context.Context) (result []*Note, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = f.NamedNotes(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = f.Edges.NotesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = f.QueryNotes().All(ctx)
	}
	return result, err
}

func (n *Note) Parent(ctx context.Context) (result []*Folder, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = n.NamedParent(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = n.Edges.ParentOrErr()
	}
	if IsNotLoaded(err) {
		result, err = n.QueryParent().All(ctx)
	}
	return result, err
}
