// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateNoteInput represents a mutation input for creating notes.
type CreateNoteInput struct {
	Title     string
	Content   string
	CreatedAt *time.Time
}

// Mutate applies the CreateNoteInput on the NoteMutation builder.
func (i *CreateNoteInput) Mutate(m *NoteMutation) {
	m.SetTitle(i.Title)
	m.SetContent(i.Content)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateNoteInput on the NoteCreate builder.
func (c *NoteCreate) SetInput(i CreateNoteInput) *NoteCreate {
	i.Mutate(c.Mutation())
	return c
}
